// staticJobs.js — All job post static data
// status: 0 = show, anything else = hide

export const STATIC_JOBS = [
  {
    id: 1,
    title: "Junior Engineer (Electrical)",
    org: "RESERVE BANK OF INDIA",
    applyLink: "https://opportunities.rbi.org.in/",
    category: "BANKS / FINANCE",
    postedDate: "Apr 16, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 4,
    qualifications: "Minimum three years Diploma in Electrical or Electrical and Electronic Engineering from a recognised Institute or University or Board with minimum 65% of marks (55% for SC/ST/PwBD) or Degree in Electrical or Electrical and Electronic Engineering from a recognised University with 55% marks (45% for SC/ST/PwBD).",
    age: "20-30",
    location: "All India",
    status: 0,
  },
  {
    id: 2,
    title: "Junior Engineer (Civil)",
    org: "RESERVE BANK OF INDIA",
    applyLink: "https://opportunities.rbi.org.in/",
    category: "BANKS / FINANCE",
    postedDate: "Apr 16, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 7,
    qualifications: "Minimum three years Diploma in Civil Engineering from a recognised Institute or University or Board with minimum 65% of marks (55% for SC/ST/PwBD) or Degree in Civil Engineering from a recognised University with 55% marks (45% for SC/ST/PwBD).",
    age: "20-30",
    location: "All India",
    status: 0,
  },
  {
    id: 3,
    title: "Perfusionist",
    org: "BROADCAST ENGINEERING CONSULTANT INDIA LIMITED",
    applyLink: "https://www.becil.com/Vacancies",
    category: "MINISTRY OF INFORMATION AND BROADCASTING",
    postedDate: "Apr 16, 2026",
    lastDate: "2026-04-27",
    noOfPosts: 2,
    qualifications: "B.Sc Degree from a recognized University.",
    age: "18-40",
    location: "All India",
    status: 0,
  },
  {
    id: 4,
    title: "Medical Lab Technician (MLT)",
    org: "BROADCAST ENGINEERING CONSULTANT INDIA LIMITED",
    applyLink: "https://www.becil.com/Vacancies",
    category: "MINISTRY OF INFORMATION AND BROADCASTING",
    postedDate: "Apr 16, 2026",
    lastDate: "2026-04-27",
    noOfPosts: 26,
    qualifications: "B.Sc in Medical Lab Technology from recognized Institute or University.",
    age: "21-35",
    location: "All India",
    status: 0,
  },
  {
    id: 5,
    title: "Research Intern",
    org: "NIRDPR",
    applyLink: "https://career.nirdpr.in/",
    category: "CENTRAL",
    postedDate: "Apr 15, 2026",
    lastDate: "2026-04-17",
    noOfPosts: 2,
    qualifications: "Final year students of Undergraduate (UG) programs in Social Sciences OR Candidates who have completed UG in Social Science disciplines (Rural Development, Economics, Sociology, Social Work, Public Administration, Public Policy, etc.).",
    age: "18-25",
    location: "All India",
    status: 0,
  },
  {
    id: 6,
    title: "Selection Post Phase-XIV/2026 (Various Government Posts)",
    org: "STAFF SELECTION COMMISSION",
    applyLink: "https://ssc.gov.in/",
    category: "STAFF SELECTION COMMISSION",
    postedDate: "Apr 14, 2026",
    lastDate: "2026-05-04",
    noOfPosts: 3003,
    qualifications: "10th / 12th / Graduate (varies by post).",
    age: "18-30",
    location: "All India",
    status: 0,
  },
  {
    id: 7,
    title: "Project Junior Research Fellow (JRF)",
    org: "CENTRAL SALT & MARINE CHEMICALS RESEARCH INSTITUTE",
    applyLink: "https://www.csmcri.res.in/",
    category: "CSIR",
    postedDate: "Apr 14, 2026",
    lastDate: "2026-04-24",
    noOfPosts: 3,
    qualifications: "M.Sc. in Chemistry.",
    age: "18-37",
    location: "Gujarat",
    status: 0,
  },
  {
    id: 8,
    title: "O&G Specialist",
    org: "NTPC LIMITED",
    applyLink: "https://ntpc.co.in/career-growth",
    category: "PSU",
    postedDate: "Apr 9, 2026",
    lastDate: "2026-04-23",
    noOfPosts: 8,
    qualifications: "MD/DNB in Obstetrics & Gynaecology.",
    age: "18-37",
    location: "All India",
    status: 0,
  },
  {
    id: 9,
    title: "Ophthalmologist",
    org: "NTPC LIMITED",
    applyLink: "https://ntpc.co.in/career-growth",
    category: "PSU",
    postedDate: "Apr 9, 2026",
    lastDate: "2026-04-23",
    noOfPosts: 1,
    qualifications: "MD/DNB in Ophthalmology.",
    age: "18-37",
    location: "All India",
    status: 0,
  },
  {
    id: 10,
    title: "Paediatrician",
    org: "NTPC LIMITED",
    applyLink: "https://ntpc.co.in/career-growth",
    category: "PSU",
    postedDate: "Apr 9, 2026",
    lastDate: "2026-04-23",
    noOfPosts: 1,
    qualifications: "MD/DNB in Paediatrics.",
    age: "18-37",
    location: "All India",
    status: 0,
  },
  {
    id: 11,
    title: "Physician (General Medicine)",
    org: "NTPC LIMITED",
    applyLink: "https://ntpc.co.in/career-growth",
    category: "PSU",
    postedDate: "Apr 9, 2026",
    lastDate: "2026-04-23",
    noOfPosts: 25,
    qualifications: "MD/DNB in General Medicine.",
    age: "18-37",
    location: "All India",
    status: 0,
  },
  {
    id: 12,
    title: "GDMO",
    org: "NTPC LIMITED",
    applyLink: "https://ntpc.co.in/career-growth",
    category: "PSU",
    postedDate: "Apr 9, 2026",
    lastDate: "2026-04-23",
    noOfPosts: 20,
    qualifications: "MBBS from a recognised University/Institution.",
    age: "18-37",
    location: "All India",
    status: 0,
  },
  {
    id: 13,
    title: "Assistant Foreman (Electrical) Grade C",
    org: "SOUTH EASTERN COALFIELD LIMITED",
    applyLink: "https://secl-cil.in/career.php",
    category: "MINISTRY OF COAL",
    postedDate: "Apr 15, 2026",
    lastDate: "2026-05-14",
    noOfPosts: 435,
    qualifications: "Matriculate or equivalent + Diploma or relevant qualification (Min 3 years) in Electrical Engineering from Government recognised Institute.",
    age: "18-30",
    location: "Chhattisgarh / MP",
    status: 0,
  },
  {
    id: 14,
    title: "Dy. Surveyor T&S Grade-C (Mining)",
    org: "SOUTH EASTERN COALFIELD LIMITED",
    applyLink: "https://secl-cil.in/career.php",
    category: "MINISTRY OF COAL",
    postedDate: "Apr 15, 2026",
    lastDate: "2026-05-14",
    noOfPosts: 43,
    qualifications: "Matriculate or equivalent + Degree/Diploma in Mining/Mine Surveying Engineering + Surveyors' Certificate of Competency (Un-Restricted) under CMR 2017.",
    age: "18-30",
    location: "Chhattisgarh / MP",
    status: 0,
  },
  {
    id: 15,
    title: "Mining Sirdar T&S Grade-C",
    org: "SOUTH EASTERN COALFIELD LIMITED",
    applyLink: "https://secl-cil.in/career.php",
    category: "MINISTRY OF COAL",
    postedDate: "Apr 15, 2026",
    lastDate: "2026-05-14",
    noOfPosts: 577,
    qualifications: "Matriculate + Diploma/Degree in Mining Engineering + Valid Mining Sirdarship Certificate of Competency (Un-Restricted) + Valid Gas Testing Certificate + Valid First Aid Certificate.",
    age: "18-30",
    location: "Chhattisgarh / MP",
    status: 0,
  },
  {
    id: 16,
    title: "Executive Director (M-11 Grade)",
    org: "NMDC LIMITED",
    applyLink: "https://www.nmdc.co.in/careers",
    category: "PSU",
    postedDate: "Mar 31, 2026",
    lastDate: "2026-04-20",
    noOfPosts: 1,
    qualifications: "Engineering Graduate (Metallurgical or Mechanical) with strong academic record + Minimum experience in O&M.",
    age: "50-57",
    location: "All India",
    status: 0,
  },
  {
    id: 17,
    title: "Livestock Officer",
    org: "UNION PUBLIC SERVICE COMMISSION",
    applyLink: "https://upsconline.gov.in/",
    category: "UPSC",
    postedDate: "Apr 11, 2026",
    lastDate: "2026-05-01",
    noOfPosts: 8,
    qualifications: "Bachelor's in Veterinary Science & Animal Husbandry + Registration with Veterinary Council of India.",
    age: "18-35",
    location: "All India",
    status: 0,
  },
  {
    id: 18,
    title: "Senior Store Officer Grade-II",
    org: "UNION PUBLIC SERVICE COMMISSION",
    applyLink: "https://upsconline.gov.in/",
    category: "UPSC",
    postedDate: "Apr 11, 2026",
    lastDate: "2026-05-01",
    noOfPosts: 7,
    qualifications: "Master's in Economics/Commerce/Statistics/Business Studies/Public Administration OR Bachelor's + Diploma in Materials Mgmt/Warehousing/Purchasing/Logistics/Public Procurement.",
    age: "18-40",
    location: "All India",
    status: 0,
  },
  {
    id: 19,
    title: "Assistant Keeper",
    org: "UNION PUBLIC SERVICE COMMISSION",
    applyLink: "https://upsconline.gov.in/",
    category: "UPSC",
    postedDate: "Apr 11, 2026",
    lastDate: "2026-05-01",
    noOfPosts: 1,
    qualifications: "Master's Degree in Anthropology + Diploma in Museology.",
    age: "18-30",
    location: "All India",
    status: 0,
  },
  {
    id: 20,
    title: "Assistant (Secretarial Service)",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 7, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 6,
    qualifications: "BBA (Bachelor of Business Administration). Basic Knowledge of Computer is preferable.",
    age: "18-28",
    location: "All India",
    status: 0,
  },
  {
    id: 21,
    title: "Assistant (Administration)",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 7, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 2,
    qualifications: "BBA (Bachelor of Business Administration). Basic Knowledge of Computer is preferable.",
    age: "18-28",
    location: "All India",
    status: 0,
  },
  {
    id: 22,
    title: "Assistant (HR)",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 7, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 2,
    qualifications: "BBA (Bachelor of Business Administration). Basic Knowledge of Computer is preferable.",
    age: "18-28",
    location: "All India",
    status: 0,
  },
  {
    id: 23,
    title: "Accountant",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 7, 2026",
    lastDate: "2026-05-06",
    noOfPosts: 14,
    qualifications: "Intermediate of The Institute of Chartered Accountants of India (ICAI) OR The Institute of Cost Accountants of India (ICMAI).",
    age: "18-28",
    location: "All India",
    status: 0,
  },
  {
    id: 24,
    title: "Operator (Chemical) Trainee",
    org: "RASHTRIYA CHEMICALS AND FERTILIZERS LIMITED",
    applyLink: "https://rcfltd.com/hrrecruitment/",
    category: "MINISTRY OF FERTILIZERS AND CHEMICALS",
    postedDate: "Apr 11, 2026",
    lastDate: "2026-04-27",
    noOfPosts: 188,
    qualifications: "B.Sc. (Chemistry) Degree / Three Years' Diploma in Chemical Engineering/Technology / HSC (Science) and direct admission to second year/3rd Semester of Three Years' Diploma in Chemical Engineering/Technology from UGC/AICTE recognized University/Institution.",
    age: "18-30",
    location: "Maharashtra",
    status: 0,
  },
  {
    id: 25,
    title: "MTS (General)",
    org: "INDIAN ASSOCIATION FOR THE CULTIVATION OF SCIENCE",
    applyLink: "https://www.iacs.res.in/Career-Staff",
    category: "MINISTRY OF SCIENCE & TECHNOLOGY",
    postedDate: "Mar 20, 2026",
    lastDate: "2026-05-15",
    noOfPosts: 5,
    qualifications: "10th pass from a recognised Board.",
    age: "18-27",
    location: "West Bengal",
    status: 0,
  },
  {
    id: 26,
    title: "Assistant (Group B)",
    org: "INDIAN ASSOCIATION FOR THE CULTIVATION OF SCIENCE",
    applyLink: "https://www.iacs.res.in/Career-Staff",
    category: "MINISTRY OF SCIENCE & TECHNOLOGY",
    postedDate: "Mar 20, 2026",
    lastDate: "2026-05-15",
    noOfPosts: 5,
    qualifications: "Any Degree from a recognised University.",
    age: "18-30",
    location: "West Bengal",
    status: 0,
  },
  {
    id: 27,
    title: "Constable (Technical and Tradesmen and Pioneer)",
    org: "CENTRAL RESERVE POLICE FORCE",
    applyLink: "https://crpf.gov.in/Vacancy-Position",
    category: "POLICE RECRUITMENT",
    postedDate: "Apr 20, 2026",
    lastDate: "2026-05-19",
    noOfPosts: 353,
    qualifications: "10th pass from a recognised Board.",
    age: "21-27",
    location: "All India",
    status: 0,
  },
  {
    id: 28,
    title: "Agniveer (Musician)",
    org: "JOIN INDIAN NAVY",
    applyLink: "https://www.joinindiannavy.gov.in/",
    category: "MINISTRY OF DEFENCE",
    postedDate: "Apr 11, 2026",
    lastDate: "2026-04-26",
    noOfPosts: 13,
    qualifications: "Matriculation Examination with minimum 50% marks in aggregate from Boards of School Education recognised by Ministry of Education, Govt. of India.",
    age: "18-22",
    location: "All India",
    status: 0,
  },
  {
    id: 29,
    title: "Senior Manager (Civil) E-4 Grade",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 1, 2026",
    lastDate: "2026-04-30",
    noOfPosts: 2,
    qualifications: "Full time 4-year regular B.E./B.Tech (Civil). Preference to Govt. Engineering Institutes (National Importance). Post-graduate Degree/Diploma in Construction Management preferred.",
    age: "18-40",
    location: "All India",
    status: 0,
  },
  {
    id: 30,
    title: "Manager (Civil) E-3 Grade",
    org: "MECON LIMITED",
    applyLink: "https://careers.meconlimited.co.in/",
    category: "MINISTRY OF STEEL",
    postedDate: "Apr 1, 2026",
    lastDate: "2026-04-30",
    noOfPosts: 2,
    qualifications: "Full time 4-year regular B.E./B.Tech (Civil). Preference to Govt. Engineering Institutes (National Importance). Post-graduate Degree/Diploma in Construction Management preferred.",
    age: "18-36",
    location: "All India",
    status: 0,
  },
  {
    id: 31,
    title: "Assistant Manager (Finance) – E1",
    org: "INDIAN RAILWAY FINANCE CORPORATION",
    applyLink: "https://irfc.co.in/active-jobs",
    category: "PSU",
    postedDate: "Apr 4, 2026",
    lastDate: "2026-05-01",
    noOfPosts: 7,
    qualifications: "B.Com from a recognised University.",
    age: "18-30",
    location: "All India",
    status: 0,
  },
  {
    id: 32,
    title: "Assistant (NE5 Level)",
    org: "INDIAN RAILWAY FINANCE CORPORATION",
    applyLink: "https://irfc.co.in/active-jobs",
    category: "PSU",
    postedDate: "Apr 4, 2026",
    lastDate: "2026-05-01",
    noOfPosts: 16,
    qualifications: "B.Com from a recognised University.",
    age: "18-30",
    location: "All India",
    status: 0,
  },
  {
    id: 35,
    title: "Senior Artisan on Contract (SA-C)",
    org: "ELECTRONICS CORPORATION OF INDIA LIMITED",
    applyLink: "https://www.ecil.co.in/",
    category: "DEPARTMENT OF ATOMIC ENERGY",
    postedDate: "Mar 26, 2026",
    lastDate: "2026-04-18",
    noOfPosts: 7,
    qualifications: "ITI in Electronics / Electrician / Electronic Mechanic / Instrumentation / Radio & TV.",
    age: "18-30",
    location: "Hyderabad",
    status: 0,
  },
  {
    id: 36,
    title: "Assistant Project Engineer on Contract (APE-C)",
    org: "ELECTRONICS CORPORATION OF INDIA LIMITED",
    applyLink: "https://www.ecil.co.in/",
    category: "DEPARTMENT OF ATOMIC ENERGY",
    postedDate: "Mar 26, 2026",
    lastDate: "2026-04-18",
    noOfPosts: 3,
    qualifications: "Diploma in ECE/ETC/Electronics from a recognised Institute.",
    age: "18-30",
    location: "Hyderabad",
    status: 0,
  },
  {
    id: 37,
    title: "Technical Officer on Contract (TO-C)",
    org: "ELECTRONICS CORPORATION OF INDIA LIMITED",
    applyLink: "https://www.ecil.co.in/",
    category: "DEPARTMENT OF ATOMIC ENERGY",
    postedDate: "Mar 26, 2026",
    lastDate: "2026-04-18",
    noOfPosts: 8,
    qualifications: "BE / B.Tech from a recognised University.",
    age: "18-30",
    location: "Hyderabad",
    status: 0,
  },
  {
    id: 38,
    title: "Project Engineer on Contract (PE-C)",
    org: "ELECTRONICS CORPORATION OF INDIA LIMITED",
    applyLink: "https://www.ecil.co.in/",
    category: "DEPARTMENT OF ATOMIC ENERGY",
    postedDate: "Mar 26, 2026",
    lastDate: "2026-04-18",
    noOfPosts: 14,
    qualifications: "BE / B.Tech from a recognised University.",
    age: "18-33",
    location: "Hyderabad",
    status: 0,
  },
  {
    id: 40,
    title: "Project Associate-I",
    org: "NATIONAL INSTITUTE OF TECHNOLOGY WARANGAL",
    applyLink: "https://nitw.ac.in/staffrecruit",
    category: "NIT",
    postedDate: "Mar 30, 2026",
    lastDate: "2026-04-17",
    noOfPosts: 1,
    qualifications: "B.Tech / B.E from a recognised University.",
    age: "18-30",
    location: "Telangana",
    status: 0,
  },
];

// All unique categories from the data
export const JOB_CATEGORIES = [
  "All",
  "BANKS / FINANCE",
  "STAFF SELECTION COMMISSION",
  "UPSC",
  "PSU",
  "MINISTRY OF COAL",
  "MINISTRY OF STEEL",
  "MINISTRY OF DEFENCE",
  "MINISTRY OF SCIENCE & TECHNOLOGY",
  "MINISTRY OF INFORMATION AND BROADCASTING",
  "MINISTRY OF FERTILIZERS AND CHEMICALS",
  "DEPARTMENT OF ATOMIC ENERGY",
  "POLICE RECRUITMENT",
  "CSIR",
  "CENTRAL",
  "NIT",
];