name: Deploy Frontend

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            APP_DIR="/home/ubuntu/apps/careermitra/prod/fe"
            BRANCH="main"
          else
            APP_DIR="/home/ubuntu/apps/careermitra/staging/fe"
            BRANCH="staging"
          fi

          cd $APP_DIR

          git fetch origin
          git checkout $BRANCH
          git pull origin $BRANCH

          cd ..

          docker compose build frontend
          docker compose up -d frontend
